"""``isth report`` — self-contained static HTML report over the runs in ``results/``.

Walks the commit-first results tree, distills every run into a compact JSON
record (reusing the same parsers as ``analyze``/``explain``), and renders a
single ``report/index.html`` with client-side Plotly charts: cross-commit
trends, model-vs-model comparison, a per-task heatmap with run drill-down, and
token/duration distributions. Because the data is embedded and the charts are
rendered in the browser, the page is fully interactive (filters, metric
switcher) while remaining a *static* artifact — it can be hosted as an HF
static Space with no server and no secrets.

The output directory (``report/``: ``index.html`` + ``plotly.min.js`` +
``README.md`` with ``sdk: static`` frontmatter) is complete Space content —
push it with ``isth report --push`` or by adding the Space as a git remote.
Pushing follows the same conventions as ``sync``/``upload``: nothing leaves
the machine unless ``--push`` is passed explicitly.
"""

from __future__ import annotations

import datetime as dt
import json
import subprocess
import urllib.request
from pathlib import Path

from .analyze import _run_path, bucket as bucket_label, parse as parse_run
from .log import log
from .paths import package_data_path, state_root
from .run_task import load_tasks
from .sync import _git_meta, write_manifest
from .transcript import parse_transcript
from .upload import _have_hf_cli
from .util import read_meta

# Truncation budgets for embedded text (traces are untrusted + size matters).
FINAL_MAX = 400   # final-answer snippet
BASH_MAX = 120    # Bash command preview per step
ERR_MAX = 140     # error-result snippet per errored step

DEFAULT_SPACE = "lysandre/transformers-agentic-use-report"
DEFAULT_BUCKET = "lysandre/transformers-agentic-use"

# Pinned and placed next to index.html at generate time so the published Space
# is self-contained; falls back to the CDN reference if the fetch fails.
PLOTLY_CDN = "https://cdn.plot.ly/plotly-2.35.2.min.js"

_SPACE_README = """---
title: transformers agentic-use report
emoji: 📊
colorFrom: yellow
colorTo: indigo
sdk: static
pinned: false
---

# transformers agentic-use — run report

Static report generated by [`isth report`](https://github.com/huggingface/is-transformers-agentic-enough)
over the runs synced to the `{bucket}` bucket.

Regenerate and republish:

```bash
isth report --pull --push
```
"""


# --------- collection ---------


def _ref_label(root, sha: str) -> tuple[str | None, str | None, str]:
    """``(experiment_name, ref_name, kind)`` for a commit, ``kind`` ∈ branch|tag|commit.

    Prefers the ``ref.json`` marker written at run time (what the user actually
    asked to test, plus any ``--name`` title). For older data without a marker,
    falls back to a release tag pointing at the commit; otherwise it's a plain
    commit.
    """
    info = read_meta(root / sha / "ref.json") or {}
    name = info.get("name")
    kind = info.get("kind")
    if kind in ("branch", "tag"):
        return name, info.get("ref"), kind
    if kind == "commit":
        return name, None, "commit"
    # No marker (pre-feature data): is a tag pointing at this commit?
    try:
        from .paths import transformers_src
        import subprocess

        out = subprocess.check_output(
            ["git", "-C", str(transformers_src()), "tag", "--points-at", sha],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if out:
            return name, out.splitlines()[0], "tag"
    except (Exception, SystemExit):
        pass
    return name, None, "commit"


def _step_record(step) -> dict:
    """Compact per-step record for the drill-down timeline. Non-error results
    are NOT embedded (the main size lever); errors carry a short snippet."""
    rec: dict = {"b": bucket_label(step.name, step.input), "n": step.name, "e": step.is_error}
    if step.name == "Bash":
        rec["x"] = (step.input.get("command") or "").replace("\n", " ⏎ ")[:BASH_MAX]
    elif step.name in ("Read", "Write", "Edit"):
        rec["x"] = step.input.get("file_path") or ""
    else:
        rec["x"] = ""
    if step.is_error:
        lines = [ln for ln in step.result.splitlines() if ln.strip()]
        rec["r"] = (lines[0] if lines else "")[:ERR_MAX]
    return rec


def _run_record(jsonl: Path, sha: str, harness: str, model_id: str,
                variant: str, task: str, run_idx: int) -> dict:
    run = parse_run(jsonl, task)
    tx = parse_transcript(jsonl)
    return {
        "sha": sha,
        "ns": f"{harness}/{model_id}",
        "harness": harness,
        "model_id": model_id,
        "variant": variant,
        "task": task,
        "run": run_idx,
        "status": run.status,
        "exit": run.exit_code,
        "approach": _run_path(run),
        "retry": run.errored_calls > 0,
        "calls": len(run.tool_calls),
        "errs": run.errored_calls,
        "matched": run.matched_expected,
        "first_success": run.first_success_turn,
        "elapsed": run.elapsed,
        "tok": {
            "new": run.tokens_in + run.tokens_cache_creation,
            "rep": run.tokens_cache_read,
            "out": run.tokens_out,
        },
        "trace_rel": f"{sha}/{harness}/{model_id}/{jsonl.name}",
        "final": (run.final or "")[:FINAL_MAX],
        "steps": [_step_record(s) for s in tx.steps],
    }


def collect_records(refs: list[str] | None = None, bucket: str = DEFAULT_BUCKET) -> dict:
    """Build the payload embedded in the HTML: tasks, date-ordered commits,
    namespaces, and one record per run found under ``results/``."""
    root = state_root() / "results"
    runs: list[dict] = []
    shas: set[str] = set()
    namespaces: set[str] = set()

    for jsonl in sorted(root.glob("*/*/*/*.jsonl")):
        sha, harness, model_id, _fname = jsonl.relative_to(root).parts
        if refs and sha not in refs:
            continue
        try:
            variant, task, runtok = jsonl.stem.split("__")
        except ValueError:
            continue  # unexpected filename; skip
        run_idx = int(runtok.replace("run", "") or 0)
        runs.append(_run_record(jsonl, sha, harness, model_id, variant, task, run_idx))
        shas.add(sha)
        namespaces.add(f"{harness}/{model_id}")

    # Commit metadata: prefer the (freshly written) manifest, fall back to git.
    manifest: dict = {}
    mpath = root / "MANIFEST.json"
    if mpath.exists():
        try:
            manifest = json.loads(mpath.read_text()).get("commits", {})
        except Exception:
            manifest = {}
    commits = []
    for sha in sorted(shas):
        meta = manifest.get(sha) or {}
        subject, date = meta.get("subject"), meta.get("date")
        if not subject or subject == "?":
            subject, date = _git_meta(sha)
        name, ref, kind = _ref_label(root, sha)
        commits.append({"sha": sha, "subject": subject, "date": date or "?",
                        "name": name, "ref": ref, "kind": kind})
    commits.sort(key=lambda c: (c["date"], c["sha"]))

    tasks_meta = [
        {"id": tid, "category": t.get("category"), "expected": t.get("expected")}
        for tid, t in load_tasks().items()
    ]
    return {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "bucket": bucket,
        "tasks": tasks_meta,
        "commits": commits,
        "namespaces": sorted(namespaces),
        "runs": runs,
    }


# --------- rendering ---------


def _ensure_plotly(out_dir: Path) -> str:
    """Place ``plotly.min.js`` next to index.html (download once, cached);
    return the ``<script src>`` to embed — the CDN URL if the fetch failed."""
    target = out_dir / "plotly.min.js"
    if target.exists() and target.stat().st_size > 0:
        return "plotly.min.js"
    try:
        log(f"fetching {PLOTLY_CDN} …")
        with urllib.request.urlopen(PLOTLY_CDN, timeout=30) as resp:
            target.write_bytes(resp.read())
        return "plotly.min.js"
    except Exception as e:  # noqa: BLE001
        log(f"  (could not fetch plotly: {e}; the report will reference the CDN)")
        return PLOTLY_CDN


def render(payload: dict, out_dir: Path, bucket: str = DEFAULT_BUCKET) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    template = package_data_path("report.html").read_text()
    # `</` must not terminate the embedding <script> block early.
    data = json.dumps(payload, separators=(",", ":")).replace("</", "<\\/")
    plotly_src = _ensure_plotly(out_dir)
    html = template.replace("__PLOTLY_SRC__", plotly_src).replace("__ISTH_DATA__", data)
    index = out_dir / "index.html"
    index.write_text(html)
    (out_dir / "README.md").write_text(_SPACE_README.format(bucket=bucket))
    return index


# --------- orchestration ---------


def report(
    refs: list[str] | None = None,
    *,
    pull: bool = False,
    push: bool = False,
    space_id: str = DEFAULT_SPACE,
    public: bool = False,
    open_browser: bool = False,
    bucket: str = DEFAULT_BUCKET,
) -> int:
    if pull:
        from .sync import sync

        rc = sync(bucket, pull=True)
        if rc != 0:
            return rc

    write_manifest()  # keep commit subjects/dates fresh for ordering
    payload = collect_records(refs, bucket=bucket)
    if not payload["runs"]:
        log("no runs found under results/ — run a suite, or `isth report --pull` first")
        return 1

    out_dir = state_root() / "report"
    index = render(payload, out_dir, bucket=bucket)
    log(
        f"report: {len(payload['runs'])} runs, {len(payload['commits'])} commit(s), "
        f"{len(payload['namespaces'])} namespace(s)"
    )
    log(f"→ {index}")

    if open_browser:
        import webbrowser

        webbrowser.open(index.as_uri())

    cmd = ["hf", "upload", space_id, str(out_dir), ".", "--repo-type", "space"]
    if not public:
        cmd.append("--private")
    log("push plan (static Space):")
    log("  " + " ".join(cmd))
    if not push:
        log(
            "not pushed — re-run with `--push` to publish, or push the report/ "
            "dir to a Space git remote yourself."
        )
        return 0

    if not _have_hf_cli():
        log("The `hf` CLI is not installed. Install it with "
            "`curl -LsSf https://hf.co/cli/install.sh | bash` and `hf auth login`.")
        return 1
    rc = subprocess.run(cmd).returncode
    if rc == 0:
        log(f"→ https://huggingface.co/spaces/{space_id}")
    return rc
