"""``ag report`` — self-contained static HTML report over the runs in ``results/``.

Walks the commit-first results tree, distills every run into a compact JSON
record (reusing the same parsers as ``analyze``/``explain``), and renders a
single ``report/index.html`` with client-side Plotly charts: cross-commit
trends, model-vs-model comparison, a per-task heatmap with run drill-down, and
token/duration distributions. Because the data is embedded and the charts are
rendered in the browser, the page is fully interactive (filters, metric
switcher) while remaining a *static* artifact — it can be hosted as an HF
static Space with no server and no secrets.

The output directory (``report/``: ``index.html`` + ``plotly.min.js`` +
``README.md`` with ``sdk: static`` frontmatter) is complete Space content —
push it with ``ag report --push`` or by adding the Space as a git remote.
Pushing follows the same conventions as ``sync``/``upload``: nothing leaves
the machine unless ``--push`` is passed explicitly.
"""

from __future__ import annotations

import base64
import datetime as dt
import json
import mimetypes
import re
import subprocess
import urllib.request
from pathlib import Path

# Don't inline an input bigger than this as a data URI (keeps the report lean).
# Generous enough for a short audio clip (a few MB) but guards against huge files.
MEDIA_MAX_BYTES = 8_000_000

from . import store
from .analyze import parse as parse_run, step_kind
from .markers import fired as _markers_fired
from .log import log
from .paths import package_data_path, state_root
from .run_task import load_tasks
from .sync import _git_meta, write_manifest
from .transcript import parse_events
from .upload import _have_hf_cli
from .util import read_meta

# Truncation budgets for embedded text (traces are untrusted + size matters).
FINAL_MAX = 400   # final-answer snippet
BASH_MAX = 120    # Bash command preview per step
ERR_MAX = 140     # error-result snippet per errored step

DEFAULT_SPACE = "lysandre/transformers-agentic-use-report"
DEFAULT_BUCKET = "lysandre/transformers-agentic-use"

# Pinned and placed next to index.html at generate time so the published Space
# is self-contained; falls back to the CDN reference if the fetch fails.
PLOTLY_CDN = "https://cdn.plot.ly/plotly-2.35.2.min.js"

_SPACE_README = """---
title: ag run report
emoji: 📊
colorFrom: yellow
colorTo: indigo
sdk: static
pinned: false
---

# ag — run report

Static report generated by [`ag report`](https://github.com/huggingface/is-transformers-agentic-enough)
over the runs synced to the `{bucket}` bucket.

Regenerate and republish:

```bash
ag report --pull --push
```
"""


# --------- collection ---------


def _ref_label(root, sha: str) -> tuple[str | None, str | None, str]:
    """``(experiment_name, ref_name, kind)`` for a commit, ``kind`` ∈ branch|tag|commit.

    Prefers the ``ref.json`` marker written at run time (what the user actually
    asked to test, plus any ``--name`` title). For older data without a marker,
    falls back to a release tag pointing at the commit; otherwise it's a plain
    commit.
    """
    info = read_meta(root / sha / "ref.json") or {}
    name = info.get("name")
    kind = info.get("kind")
    if kind in ("branch", "tag"):
        return name, info.get("ref"), kind
    if kind == "commit":
        return name, None, "commit"
    # No marker (pre-feature data): is a tag pointing at this commit?
    try:
        from .paths import transformers_src
        import subprocess

        out = subprocess.check_output(
            ["git", "-C", str(transformers_src()), "tag", "--points-at", sha],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if out:
            return name, out.splitlines()[0], "tag"
    except (Exception, SystemExit):
        pass
    return name, None, "commit"


def _step_record(step) -> dict:
    """Compact per-step record for the drill-down timeline. Non-error results
    are NOT embedded (the main size lever); errors carry a short snippet."""
    rec: dict = {"b": step_kind(step.name, step.input), "n": step.name, "e": step.is_error}
    if step.name == "Bash":
        rec["x"] = (step.input.get("command") or "").replace("\n", " ⏎ ")[:BASH_MAX]
    elif step.name in ("Read", "Write", "Edit"):
        rec["x"] = step.input.get("file_path") or ""
    else:
        rec["x"] = ""
    if step.is_error:
        lines = [ln for ln in step.result.splitlines() if ln.strip()]
        rec["r"] = (lines[0] if lines else "")[:ERR_MAX]
    return rec


def _run_record(rec, sha: str, harness: str, model_id: str, markers: list) -> dict:
    run = parse_run(rec, rec.task)
    tx = parse_events(rec.events)
    fired = _markers_fired(markers, run)
    return {
        "sha": sha,
        "ns": f"{harness}/{model_id}",
        "harness": harness,
        "model_id": model_id,
        "tier": rec.tier,
        "task": rec.task,
        "run": rec.run,
        "status": run.status,
        "exit": run.exit_code,
        "markers": [name for name, hit in fired.items() if hit],
        "retry": run.errored_calls > 0,
        "calls": len(run.tool_calls),
        "errs": run.errored_calls,
        "matched": run.matched_expected,
        "first_success": run.first_success_turn,
        "elapsed": run.elapsed,
        "tok": {
            "new": run.tokens_in + run.tokens_cache_creation,
            "rep": run.tokens_cache_read,
            "out": run.tokens_out,
        },
        "trace_rel": f"{sha}/{harness}/{model_id}.jsonl",
        "final": (run.final or "")[:FINAL_MAX],
        "steps": [_step_record(s) for s in tx.steps],
    }


def _model_params(namespaces: set[str]) -> dict[str, int]:
    """Best-effort total parameter count per namespace via the Hub's safetensors
    metadata, so the report can order models by true size rather than guessing
    from the id. Each namespace is ``<harness>/<model_id>`` with ``/`` in the
    model id encoded as ``--``. Failures (offline, gated, nonexistent repo, no
    safetensors) are skipped silently — the report falls back to parsing a size
    out of the model id client-side."""
    out: dict[str, int] = {}
    try:
        from huggingface_hub import HfApi
    except Exception:  # noqa: BLE001
        return out
    api = HfApi()
    seen: dict[str, int | None] = {}
    for ns in namespaces:
        harness, _, model_id = ns.partition("/")
        if harness == "mock" or not model_id or model_id == "default":
            continue
        # drop any ":provider" routing suffix (e.g. "…-7B-Instruct:together")
        repo = model_id.replace("--", "/").split(":", 1)[0]
        if repo not in seen:
            try:
                st = api.model_info(repo, expand=["safetensors"]).safetensors
                seen[repo] = int(st.total) if st and st.total else None
            except Exception:  # noqa: BLE001
                seen[repo] = None
        if seen[repo]:
            out[ns] = seen[repo]
    return out


def collect_records(refs: list[str] | None = None, *, markers: list | None = None,
                    profile_name: str = "transformers", bucket: str = DEFAULT_BUCKET) -> dict:
    """Build the payload embedded in the HTML: tasks, date-ordered revisions,
    namespaces, marker names, and one record per run found under ``results/``."""
    markers = markers or []
    root = state_root() / "results"
    runs: list[dict] = []
    shas: set[str] = set()
    namespaces: set[str] = set()

    # Scope to bindings produced by this profile. ``ref.json`` records the
    # producing profile; legacy data without the key predates the mock profile
    # and is all transformers, so a missing key counts as the requested profile.
    _profile_of: dict[str, bool] = {}

    def _in_profile(sha: str) -> bool:
        if sha not in _profile_of:
            info = read_meta(root / sha / "ref.json") or {}
            _profile_of[sha] = info.get("profile", profile_name) == profile_name
        return _profile_of[sha]

    for sha, ns in store.iter_cells(refs):
        if not _in_profile(sha):
            continue
        harness, _, model_id = ns.partition("/")
        for rec in store.list_runs(sha, ns):
            runs.append(_run_record(rec, sha, harness, model_id, markers))
        shas.add(sha)
        namespaces.add(ns)

    # Commit metadata: prefer the (freshly written) manifest, fall back to git.
    manifest: dict = {}
    mpath = root / "MANIFEST.json"
    if mpath.exists():
        try:
            manifest = json.loads(mpath.read_text()).get("commits", {})
        except Exception:
            manifest = {}
    commits = []
    for sha in sorted(shas):
        meta = manifest.get(sha) or {}
        subject, date = meta.get("subject"), meta.get("date")
        if not subject or subject == "?":
            subject, date = _git_meta(sha)
        name, ref, kind = _ref_label(root, sha)
        commits.append({"sha": sha, "subject": subject, "date": date or "?",
                        "name": name, "ref": ref, "kind": kind})
    commits.sort(key=lambda c: (c["date"], c["sha"]))

    def _media_refs(prompt: str) -> list[str]:
        """Input files a prompt points at (e.g. ``./inputs/cat.jpg``)."""
        return sorted(set(re.findall(r"(?:\./)?inputs/([\w.\-]+)", prompt or "")))

    all_tasks = load_tasks()
    tasks_meta = [
        {"id": tid, "category": t.get("category"), "expected": t.get("expected"),
         "match": t.get("match") or "substring", "prompt": (t.get("prompt") or "").strip(),
         "media": _media_refs(t.get("prompt") or ""), "runs": int(t.get("runs") or 3)}
        for tid, t in all_tasks.items()
    ]
    # inline each referenced input once as a data URI so the static report can
    # show the actual image / play the actual audio with no external fetch
    inputs: dict[str, dict] = {}
    for fname in sorted({m for t in tasks_meta for m in t["media"]}):
        try:
            data = package_data_path("inputs", fname).read_bytes()
        except Exception:  # noqa: BLE001
            continue
        if len(data) > MEDIA_MAX_BYTES:
            continue
        mime = mimetypes.guess_type(fname)[0] or "application/octet-stream"
        kind = "image" if mime.startswith("image/") else "audio" if mime.startswith("audio/") else "file"
        inputs[fname] = {"kind": kind, "mime": mime,
                         "uri": f"data:{mime};base64,{base64.b64encode(data).decode()}"}
    return {
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "profile": profile_name,
        "bucket": bucket,
        "tasks": tasks_meta,
        "inputs": inputs,
        "revisions": commits,
        "namespaces": sorted(namespaces),
        "model_params": _model_params(namespaces),
        "marker_names": [m.name for m in markers],
        "marker_desc": {m.name: getattr(m, "description", "") for m in markers},
        "runs": runs,
    }


# --------- rendering ---------


def _ensure_plotly(out_dir: Path) -> str:
    """Place ``plotly.min.js`` next to index.html (download once, cached);
    return the ``<script src>`` to embed — the CDN URL if the fetch failed."""
    target = out_dir / "plotly.min.js"
    if target.exists() and target.stat().st_size > 0:
        return "plotly.min.js"
    try:
        log(f"fetching {PLOTLY_CDN} …")
        with urllib.request.urlopen(PLOTLY_CDN, timeout=30) as resp:
            target.write_bytes(resp.read())
        return "plotly.min.js"
    except Exception as e:  # noqa: BLE001
        log(f"  (could not fetch plotly: {e}; the report will reference the CDN)")
        return PLOTLY_CDN


def render(payload: dict, out_dir: Path, bucket: str = DEFAULT_BUCKET) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    template = package_data_path("report.html").read_text()
    # `</` must not terminate the embedding <script> block early.
    data = json.dumps(payload, separators=(",", ":")).replace("</", "<\\/")
    plotly_src = _ensure_plotly(out_dir)
    html = template.replace("__PLOTLY_SRC__", plotly_src).replace("__AG_DATA__", data)
    index = out_dir / "index.html"
    index.write_text(html)
    (out_dir / "README.md").write_text(_SPACE_README.format(bucket=bucket))
    return index


# --------- orchestration ---------


def report(
    refs: list[str] | None = None,
    *,
    markers: list | None = None,
    profile_name: str = "transformers",
    pull: bool = False,
    push: bool = False,
    space_id: str = DEFAULT_SPACE,
    public: bool = False,
    open_browser: bool = False,
    bucket: str = DEFAULT_BUCKET,
) -> int:
    if pull:
        from .sync import sync

        rc = sync(bucket, pull=True)
        if rc != 0:
            return rc

    write_manifest()  # keep revision subjects/dates fresh for ordering
    payload = collect_records(refs, markers=markers, profile_name=profile_name, bucket=bucket)
    if not payload["runs"]:
        log("no runs found under results/ — run a suite, or `ag report --pull` first")
        return 1

    out_dir = state_root() / "report"
    index = render(payload, out_dir, bucket=bucket)
    log(
        f"report: {len(payload['runs'])} runs, {len(payload['revisions'])} revision(s), "
        f"{len(payload['namespaces'])} namespace(s)"
    )
    log(f"→ {index}")

    if open_browser:
        import webbrowser

        webbrowser.open(index.as_uri())

    cmd = ["hf", "upload", space_id, str(out_dir), ".", "--repo-type", "space"]
    if not public:
        cmd.append("--private")
    log("push plan (static Space):")
    log("  " + " ".join(cmd))
    if not push:
        log(
            "not pushed — re-run with `--push` to publish, or push the report/ "
            "dir to a Space git remote yourself."
        )
        return 0

    if not _have_hf_cli():
        log("The `hf` CLI is not installed. Install it with "
            "`curl -LsSf https://hf.co/cli/install.sh | bash` and `hf auth login`.")
        return 1
    rc = subprocess.run(cmd).returncode
    if rc == 0:
        log(f"→ https://huggingface.co/spaces/{space_id}")
    return rc
